name: Publish Package

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for npm provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build package
        run: mise run build

      - name: Publish to npm
        run: mise run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}